#!/bin/bash
sDate=$1
eDate=$2
indir=$3
outdir=$4
landname=$5
# splitting up dates into components
sYear=$(echo $sDate | cut -c1-4)
sMonth=$(echo $sDate | cut -c5-6)
sDay=$(echo $sDate | cut -c7-8)
sHour=$(echo $sDate | cut -c9-10)
eYear=$(echo $eDate | cut -c1-4)
eMonth=$(echo $eDate | cut -c5-6)
eDay=$(echo $eDate | cut -c7-8)
eHour=$(echo $eDate | cut -c9-10)


# get the grid cells for the requested land unit
fname="/tmp/$landname.g2l"
# create a file with instruction to handle only 1 line
echo "1" > $fname
# put grid data into the file - use first one found in seg_maps
fgrep -h $landname seg_maps/* | head -n 1 >> $fname
NLDAS2_ASCII_to_LSegs $indir $outdir $sYear $sMonth $sDay $sHour $eYear $eMonth $eDay $eHour $fname

