#!/bin/bash
hourlyvarkey=$1
dailyvarkey=$2
fractionvarkey=$3
raster_sql_file=$4
db_host=$5
db_name=$6
start_date=-1
end_date=-1
if [ $# -gt 6 ]; then
  start_date=$7
fi
if [ $# -gt 7 ]; then
  end_date=$8
fi
if [ $start_date == "-1" ]; then
  start_epoch='-1'
else
  start_epoch=$(date -d $start_date +%s)
fi
if [ $end_date == "-1" ]; then
 end_epoch='-1' # Or leave it undefined
else
  end_epoch=$(date -d $end_date +%s)
fi

rastersql="
\\set hourlyvarkey '$hourlyvarkey' \n
\\set dailyvarkey '$dailyvarkey' \n
\\set fractionvarkey '$fractionvarkey' \n
\\set start_epoch $start_epoch \n
\\set end_epoch $end_epoch \n

insert into dh_timeseries_weather ( tstime,tsendtime, featureid, entity_type, rast, bbox, varid)
select hourly.tstime,hourly.tsendtime, hourly.featureid, hourly.entity_type, st_mapalgebra(
    hourly.rast, 1, 
    St_Reclass(daily.rast, 1, '[0-0]:1-1, [0.0000001-99999]:0.0000001-99999', '64BF',9999), 1, 
    '[rast1]/ [rast2]'
  ) as rast,  hourly.bbox, fraction.hydroid as varid
from dh_timeseries_weather as hourly
left outer join tmp_dh_timeseries_weather as dupe
on (
 hourly.tstime = dupe.tstime
 and hourly.tsendtime = dupe.tsendtime
 and hourly.varid = dupe.varid
 and hourly.bbox = dupe.bbox
)
Left outer join dh_timeseries_weather as daily 
on(
extract(day from to_timestamp(hourly.tsendtime)) = extract(day from to_timestamp(daily.tsendtime)) 
  and extract(year from to_timestamp(hourly.tsendtime)) = extract(year from to_timestamp(daily.tsendtime)) 
  and extract(month from to_timestamp(hourly.tsendtime)) = extract(month from to_timestamp(daily.tsendtime))
)
left outer join dh_variabledefinition as fraction 
on(
   fraction.varkey = :'fractionvarkey'
)
left outer join dh_variabledefinition as hourly_variable
on(
hourly.varid = hourly_variable.hydroid
)
left outer join dh_variabledefinition as daily_variable
on(
daily.varid = daily_variable.hydroid
)

where dupe.tid is null
AND hourly_variable.varkey= :'hourlyvarkey'
AND daily_variable.varkey= :'dailyvarkey'
AND fraction.hydroid is not null
and ( (hourly.tsendtime >=:start_epoch) or (:start_epoch = -1) )
and ( (hourly.tsendtime <=:end_epoch) or (:end_epoch = -1) )
and ( (daily.tsendtime >=:start_epoch) or (:start_epoch = -1) )
and ( (daily.tsendtime <=:end_epoch) or (:end_epoch = -1) )
;"

# turn off the expansion of the asterisk
set -f
echo -e $rastersql > $raster_sql_file 
cat $raster_sql_file | psql -h $db_host $db_name
