#!/bin/bash
hourlyvarkey=$1
dailyvarkey=$2
fractionvarkey=$3
raster_sql_file=$4
db_host=$5
db_name=$6
end_datetime="$7 $8 $9"

rastersql="
\\set hourlyvarkey '$hourlyvarkey' \n
\\set dailyvarkey '$dailyvarkey' \n
\\set fractionvarkey '$fractionvarkey' \n
\\set end_datetime '$end_datetime' \n
with dailyUnion as (
	SELECT min(daily.tstime) as tstime,
		max(daily.tsendtime) as tsendtime,
		ST_UNION(daily.rast,'sum') as rast,
		daily_variable.hydroid as varid
	FROM dh_timeseries_weather as daily
	LEFT JOIN dh_variabledefinition as daily_variable
	on (daily.varid = daily_variable.hydroid)
	WHERE daily_variable.varkey= :'dailyvarkey'
		AND ( daily.tsendtime > extract(epoch from :'end_datetime'::timestamptz) - 86400)
		AND ( daily.tsendtime <= extract(epoch from :'end_datetime'::timestamptz))
	GROUP BY daily_variable.hydroid, extract(day from to_timestamp(daily.tstime - 43200) at time zone 'UTC')
),
dailyReclass as (
	SELECT dailyUnion.tstime, dailyUnion.tsendtime,
	St_Reclass( dailyUnion.rast, 1, '[0-0]:1-1, [0.0000001-99999]:0.0000001-99999', '64BF',9999 ) as rast,
	dailyUnion.varid
	FROM dailyUnion
), frac_daily as (
	SELECT hourly.tstime,hourly.tsendtime,
		hourly.featureid, hourly.entity_type,
		st_mapalgebra(
			st_mapalgebra( hourly.rast, 1, daily.rast, 1, '[rast1]/ [rast2]' ), 1,
			St_Reclass( dailyUnion.rast, 1, '[0-0]:1-1, [0.0000001-99999]:0-0', '64BF',9999 ), 1,
			'[rast1]+ [rast2] / 24'
		) as rast,
		hourly.bbox,
		fraction.hydroid as varid
	FROM dh_timeseries_weather as hourly
	LEFT JOIN dh_variabledefinition as fraction
	ON (fraction.varkey = :'fractionvarkey')
	LEFT JOIN dailyReclass as daily
	ON (hourly.tsendtime > daily.tstime
	and hourly.tsendtime <= daily.tsendtime)
	LEFT JOIN dh_variabledefinition as hourly_variable
	on (hourly.varid = hourly_variable.hydroid)
	WHERE hourly_variable.varkey= :'hourlyvarkey'
		AND ( hourly.tsendtime > extract(epoch from :'end_datetime'::timestamptz) - 86400)
		AND ( hourly.tsendtime <= extract(epoch from :'end_datetime'::timestamptz))
)
INSERT INTO dh_timeseries_weather ( tstime,tsendtime, featureid, entity_type, rast, bbox, varid)  \n
SELECT frac.* FROM frac_daily as frac  \n
LEFT JOIN dh_timeseries_weather as dupe  \n
on (  \n
  frac.tstime = dupe.tstime  \n
  and frac.tsendtime = dupe.tsendtime  \n
  and frac.bbox = dupe.bbox  \n
  and frac.varid = dupe.varid)  \n
WHERE dupe.tid IS null;"

# turn off the expansion of the asterisk
set -f
echo -e $rastersql > $raster_sql_file 
cat $raster_sql_file | psql -h $db_host $db_name
