#!/bin/bash
hydrocode=$1
varkey=$2
raster_sql_file=$3
raster_sum_file=$4
db_host=$5
db_name=$6
start_epoch=-1
end_epoch=-1
if [ $# -gt 6 ]; then
  start_epoch=$7
fi
if [ $# -gt 7 ]; then
  end_epoch=$8
fi
echo "called calc_raster_ts $hydrocode $varkey $raster_sql_file $raster_sum_file $db_host $db_name $start_epoch $end_epoch"

raster_sql="
\\set band '1' \n
\\set varkey '$varkey' \n
\\set hydrocode  '$hydrocode' \n
\\set fname '${raster_sum_file}' \n
select hydroid as covid from dh_feature where hydrocode = 'cbp6_met_coverage' \\gset \n

\\\timing ON \n

copy ( 
	WITH usgs_features AS (
	  SELECT * 
	  FROM  dh_feature
	  WHERE hydrocode = :'hydrocode'
	),
	metUnion as (
		Select met.featureid, met.tstime,met.tsendtime,
			st_union(met.rast) as rast
		FROM usgs_features as f
		left outer join field_data_dh_geofield as fgeo
		on (
			fgeo.entity_id = f.hydroid
			and fgeo.entity_type = 'dh_feature' 
		) 
		JOIN(
			select *
			from dh_timeseries_weather as met
			left outer join dh_variabledefinition as b
				on (met.varid = b.hydroid) 
			where b.varkey=:'varkey'
				and ( (met.tstime >= $start_epoch) or ($start_epoch = -1) )
				and ( (met.tsendtime <= $end_epoch) or ($end_epoch = -1) )
				and met.featureid = :'covid'
		) AS met
		ON ST_Intersects(ST_ConvexHull(met.rast),fgeo.dh_geofield_geom)
		
		group by met.featureid, met.tsendtime
	),
	met as (
		Select met.featureid, to_timestamp(met.tsendtime) as obs_date,
			extract(year from to_timestamp(met.tsendtime)) as yr,
			extract(month from to_timestamp(met.tsendtime)) as mo,
			extract(day from to_timestamp(met.tsendtime)) as da,
			extract(hour from to_timestamp(met.tsendtime)) as hr,
			met.tstime,met.tsendtime,
			(ST_summarystats(st_clip(met.rast, fgeo.dh_geofield_geom), :'band', TRUE)).mean as stats
		FROM usgs_features as f
		left outer join field_data_dh_geofield as fgeo
		on (
			fgeo.entity_id = f.hydroid
			and fgeo.entity_type = 'dh_feature' 
		) 
		JOIN metUnion AS met
		ON ST_Intersects(ST_ConvexHull(met.rast),fgeo.dh_geofield_geom)
	)
	select featureid, obs_date, 
		tstime,tsendtime,
		yr, mo, da, hr, 
		0.0393701 * stats precip_in
	from met
	order by met.tsendtime
) to :'fname' WITH HEADER CSV;"
# turn off the expansion of the asterisk
set -f
echo -e $raster_sql > $raster_sql_file 
cat $raster_sql_file | psql -h $db_host $db_name
