#!/bin/bash
hydrocode=$1
varkey=$2
disaggregate_varkey=$3
daily_varkey=$4
raster_sql_file=$5
raster_sum_file=$6
db_host=$7
db_name=$8
bundle=$9
ftype=${10}
start_epoch=-1
end_epoch=-1
if [ $# -gt 10 ]; then
  start_epoch=${11}
fi
if [ $# -gt 11 ]; then
  end_epoch=${12}
fi
echo "called DISAGGREGATE_RASTER_TS $hydrocode $varkey $disaggregate_varkey $daily_varkey $raster_sql_file $raster_sum_file $db_host $db_name $bundle $ftype $start_epoch $end_epoch"
echo "Checking bundle as ${bundle} and type as ${ftype}"
raster_sql="
\\set band '1' \n
\\set hydrocode '$hydrocode' \n
\\set varkey '$varkey' \n
\\set disag_varkey '$disaggregate_varkey' \n
\\set daily_varkey '$daily_varkey' \n
\\set bundle '${bundle}' \n
\\set ftype '${ftype}' \n
\\set start_epoch $start_epoch \n 
\\set end_epoch $end_epoch \n
\\set fname '${raster_sum_file}' \n
select hydroid as covid from dh_feature where hydrocode = 'cbp6_met_coverage' \\gset \n
	
\\\timing ON \n
	
copy (  \n
WITH usgs_features AS (  \n
	SELECT *  \n
	FROM dh_feature_fielded  \n
	WHERE hydrocode = :'hydrocode'  \n
	AND bundle = :'bundle'  \n
	AND ftype = :'ftype'  \n
)  \n
,metUnion AS (  \n
	SELECT met.featureid,  \n
	met.tstime, met.tsendtime,  \n
	st_clip(  \n
		st_union(met.rast),  \n
		st_buffer(st_convexhull(f.dh_geofield_geom),0.125)  \n
	) as rast  \n
	FROM usgs_features as f  \n
	JOIN(  \n
		SELECT *  \n
		FROM dh_timeseries_weather as met  \n
		LEFT JOIN dh_variabledefinition as b  \n
		ON (met.varid = b.hydroid)  \n
		WHERE b.varkey=:'varkey'  \n
		AND ( (met.tsendtime >= :start_epoch) OR (:start_epoch = -1) )  \n
		AND ( (met.tsendtime <= :end_epoch) OR (:end_epoch = -1) )  \n
		AND met.featureid = :covid  \n
	) AS met  \n
	ON f.dh_geofield_geom && met.bbox  \n
	GROUP BY met.featureid, met.tsendtime, met.tstime, f.dh_geofield_geom  \n
)
,tempDisagg as (  \n
	SELECT met.featureid,  \n
	frac.tstime, frac.tsendtime,  \n
	ST_MapAlgebra(  \n
		st_clip(  
			met.rast,  
			ST_ConvexHull(f.dh_geofield_geom)  
		), 1, \n
		st_clip(  \n
			st_resample(frac.rast,met.rast),  \n
			ST_ConvexHull(f.dh_geofield_geom)  \n
		), 1,  \n
		'[rast1] * [rast2]'  \n
	) as rast  \n
	FROM usgs_features as f  \n
	JOIN dh_timeseries_weather as frac  
  ON ( \n
    f.dh_geofield_geom && frac.bbox  \n
  )
  \n
	LEFT JOIN dh_variabledefinition as vf  \n
	ON (frac.varid = vf.hydroid)  \n
	LEFT JOIN metUnion as met  \n
	ON (  \n
	frac.tstime >= met.tstime  \n
	AND frac.tsendtime <= met.tsendtime  \n
	)  \n
	WHERE vf.varkey = :'disag_varkey'  \n
	AND ( (frac.tstime >= :start_epoch) OR (:start_epoch = -1) )  \n
	AND ( (frac.tsendtime <= :end_epoch) OR (:end_epoch = -1) )  \n
)
,met as (  \n
	Select :'hydrocode' as hydrocode,  \n
	met.featureid, to_timestamp(met.tsendtime) as obs_date,  \n
	extract(year from to_timestamp(met.tsendtime)) as yr,  \n
	extract(month from to_timestamp(met.tsendtime)) as mo,  \n
	extract(day from to_timestamp(met.tsendtime)) as da,  \n
	extract(hour from to_timestamp(met.tsendtime)) as hr,  \n
	met.tstime,met.tsendtime,  \n
	(ST_summarystats(met.rast, :'band', TRUE)).mean as stats  \n
	FROM tempDisagg as met  \n
)  \n
SELECT * FROM (  \n
	SELECT hydrocode,  \n
	featureid, obs_date,  \n
	tstime,tsendtime,  \n
	yr, mo, da, hr,  \n
	0.0393701 * stats precip_in  \n
	FROM met  \n
) as metResults  \n
ORDER BY metResults.tsendtime  \n
) to :'fname' WITH HEADER CSV;"
# turn off the expansion of the asterisk
set -f
echo -e $raster_sql > $raster_sql_file 
cat $raster_sql_file | psql -h $db_host $db_name

