#!/bin/bash

echo "The year you would like to download is $1"
year=$1
echo "The day you would like to download is $2"
jDay=$2
echo "The output directory you would like to store the data is $3"
oDir=$3
tjday=`echo $(expr $jDay + 0)`
fulldate=`date -d "${year}-01-01 + $(( tjday - 1 )) days"`
echo "Full date = $fulldate"
mo=`date -d "$fulldate" '+%m'`
da=`date -d "$fulldate" '+%d'`
echo "$year $mo $da"

mkdir /tmp/$year
mkdir /tmp/$year/$jDay
cd /tmp/$year/$jDay
nldas_url_base="https://data.gesdisc.earthdata.nasa.gov/data/NLDAS/NLDAS_FORB0125_H.2.0"
#nldas_url_base="https://data.gesdisc.earthdata.nasa.gov/data/NLDAS/NLDAS_FORA0125_H.2.0"
fext="nc"
fver="020"
# downloading the data
ok=1
for i in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23; do 
  fpath=$nldas_url_base/$year/$jDay
  fname=NLDAS_FORB0125_H.A${year}${mo}${da}.${i}00.${fver}.${fext}
#  fname=NLDAS_FORA0125_H.A${year}${mo}${da}.${i}00.${fver}.${fext}
  cmd="wget --load-cookies .urs_cookies --save-cookies .urs_cookies --keep-session-cookies $fpath/$fname"
  echo "****** ${year}-${mo}-${da} hour: ${i}"
  echo "Running: $cmd"
  $cmd
  if [ ! -f $fname ]; then
    ok=0
  else 
    echo "$fname downloaded"
    echo "Installing: install -D $fname $oDir/$year/$jDay/$fname "
    install -D $fname $oDir/$year/$jDay/$fname 
  fi
done
if [ "$ok" == "0" ]; then
  echo "Only half day found. Exiting."
  rm -Rf $oDir/$jDay
 #rm -r ./-R
  exit
fi
# deleting temp directory
rm -Rf /tmp/$year/$jday
