#!/bin/bash

yr=$1
if [ $# -lt 1 ]; then
  echo "Usage: get_nldas_to_dat year [ending jday=today] [force=0]"
  exit
fi

# guess default day till as todays Julian day
day_till=`date +%j`
if [ $# -gt 1 ]; then
  day_till=$2
fi

echo "Trying to retrieve NLDAS data up till day $day_till of year $yr"

# check if last year is actually complete before tackling this year
last_year=$(($yr - 1))
last_year_last_jday=`date -d "${last_year}1231" +%j`
last_last_day=`ls $last_year/ | sort -nr | head -n1`
if [ $last_last_day -lt $last_year_last_jday ]; then
  ./get_nldas_to_date $last_year $last_year_last_jday
fi

last_day=`ls $yr/ | sort -nr | head -n1`
last_day=$(($last_day + 1))

while [ $last_day -le $day_till ]; do
  f_day=`printf "%03d" $last_day`
  echo "get_nldas_data.bash $yr $f_day $yr"
  ./get_nldas_data.bash $yr $f_day $yr
  last_day=$(($last_day + 1))
done
