#!/bin/bash
. hspf_config
if [ $# -eq 0 ]; then
  echo "Use: make_met2date basin/landseg sdate edate update_years(multiple ok \"yr1 yr2 ...\") [mode=basin,landseg]"
  exit
fi
basin=$1
sdate=$2
edate=$3
update_years=$4
if [ $# -gt 4 ]; then
  mode=$5
else
  mode='basin'
fi
endyear=`date +%Y`
sdatemins="${sdate}00"
edatemins="${edate}23"
basedir=$NLDAS_ROOT
outdir="$basedir/out/grid_met_csv"
lsegdir="$basedir/out/lseg_csv"
# generate full met time period (needed due to potential updates in RNMax)

if [ "$mode" == "basin" ]; then
  segs=`cbp get_landsegs $basin`
else
  # assumes a single land seg has been passed in
  segs=$basin
fi
echo "mode=$mode, segs=$segs"
cd /backup/meteorology
for i in $segs; do
  # handle the grid2land due to an error
  for yr in $update_years; do
  # get the last julian day of the year in question
    echo "Updating $i for $yr"
    jday=`/backup/meteorology/get_last_nldas_jday $yr`
    echo "jday from nldas $jday"
    data_start="${yr}0101"
    # note: 
    #   - use should have their stuff together on the date, and subtract a day from it since the last day
    #     from NLDAS is usually incomplete. so should be nldas jday minus 1, but we must trust here
    if [ $yr -eq $endyear ]; then
      jday=`date -d "$edate" +%j`
      echo "jday final $jday"
      echo "Using requested end data as jday $edate"
      data_end=`date -d "$data_start +$(( 10#$jday ))days" +%Y%m%d`
    else
      data_end="${yr}1231"
    fi
    echo "grid2land.sh $data_start $data_end $basedir $outdir $i"
    grid2land.sh $data_start $data_end $basedir $outdir $i
  done
  cd /opt/model/p6/vadeq
  # convert grid CSVs into land segment CSVs
  echo "Create data: a2l_one $sdatemins $edatemins $outdir $lsegdir $i"
  a2l_one $sdatemins $edatemins $outdir $lsegdir $i
  # update long term averages
  LongTermAvgRNMax $lsegdir/met2date $lsegdir/RNMax 1 $i
done

# set up the met2date
rm /backup/meteorology/out/lseg_csv/met2date
ln -s /backup/meteorology/out/lseg_csv/${sdatemins}-${edatemins} /backup/meteorology/out/lseg_csv/met2date
