#!/bin/bash
cov_hydrocode=$1
amalgamate_scenario=$2
amalgamate_varkey=$3

sql="UPDATE dh_timeseries_weather set featureid = foo.fid, entity_type = 'dh_feature',
  varid = foo.newvarid
FROM  (
  SELECT feat.hydroid AS fid, scen.pid AS scenariopid, avar.hydroid AS newvarid, ovar.hydroid AS oldvarid
  FROM dh_properties AS scen
  LEFT JOIN dh_properties AS model
  ON model.pid = scen.featureid
  LEFT JOIN dh_feature AS feat
  on feat.hydroid = model.featureid
  LEFT JOIN dh_variabledefinition AS avar
  on (
    avar.varkey = scen.propname
  )
  LEFT JOIN dh_variabledefinition AS ovar
  on (
    ovar.varkey = '$amalgamate_varkey'
  )
  WHERE feat.hydrocode = $cov_hydrocode
 and scen.propname = '$amalgamate_scenario'
) as foo
WHERE entity_type = 'dh_properties'  
  AND featureid = foo.scenariopid 
  AND varid = oldvarid
  AND foo.newvarid IS NOT NULL 
;"
