#!/bin/bash
if [ $# -lt 7 ]; then
  echo "Use: resampled_raster_ts hydrocode ftype varkey resample_varkey raster_sql_file raster_sum_file db_host db_name [start_epoch] [end_epoch]"
  exit
fi
hydrocode=$1
ftype=$2
varkey=$3
resample_varkey=$4
raster_sql_file=$5
raster_sum_file=$6
db_host=$7
db_name=$8
start_epoch=-1
end_epoch=-1
if [ $# -gt 8 ]; then
  start_epoch=$9
fi
if [ $# -gt 9 ]; then
  end_epoch=${10}
fi
echo "called resampled_raster_ts $hydrocode $ftype $varkey $resample_varkey $raster_sql_file $raster_sum_file $db_host $db_name $start_epoch $end_epoch"

raster_sql="\\set band '1' \n
\\set ftype '$ftype' \n
\\set varkey '$varkey' \n
\\set resample_varkey '$resample_varkey' \n
\\set hydrocode  '$hydrocode' \n
\\set fname '${raster_sum_file}' \n
\\set start_epoch $start_epoch \n
\\set end_epoch $end_epoch \n

select hydroid as covid from dh_feature where hydrocode = 'cbp6_met_coverage' \\gset \n


\\\timing ON \n

copy ( 
	WITH usgs_features AS (
	  SELECT * 
	  FROM  dh_feature
	  WHERE hydrocode = :'hydrocode'
          AND ftype = :'ftype'
	),
	metUnion as (
		Select met.featureid, met.tstime, met.tsendtime,
			st_union(met.rast) as rast
		FROM usgs_features as f
		left outer join field_data_dh_geofield as fgeo
		on (
			fgeo.entity_id = f.hydroid
			and fgeo.entity_type = 'dh_feature' 
		) 
		JOIN(
			select *
			from dh_timeseries_weather as met
			left outer join dh_variabledefinition as b
				on (met.varid = b.hydroid) 
			where b.varkey=:'varkey'
				and ( (met.tstime >= $start_epoch) or ($start_epoch = -1) )
				and ( (met.tsendtime <= $end_epoch) or ($end_epoch = -1) )
				and met.featureid = :covid
		) AS met
		ON fgeo.dh_geofield_geom && met.bbox
		
		group by met.featureid, met.tsendtime, met.tstime
	),
	met as (
		Select met.featureid, to_timestamp(met.tsendtime) as obs_date,
			extract(year from to_timestamp(met.tsendtime)) as yr,
			extract(month from to_timestamp(met.tsendtime)) as mo,
			extract(day from to_timestamp(met.tsendtime)) as da,
			extract(hour from to_timestamp(met.tsendtime)) as hr,
			met.tstime,met.tsendtime,
			(ST_summarystats(st_clip(st_resample(met.rast,rt.rast), fgeo.dh_geofield_geom), :'band', TRUE)).mean as stats
		FROM usgs_features as f
		left outer join field_data_dh_geofield as fgeo
		on (
			fgeo.entity_id = f.hydroid
			and fgeo.entity_type = 'dh_feature' 
		) 
		JOIN metUnion AS met
		ON ST_Intersects(ST_ConvexHull(met.rast),fgeo.dh_geofield_geom)
		left join (select rast from raster_templates where varkey = :'resample_varkey') as rt
		ON 1 = 1
	)
	select featureid, obs_date, 
		tstime,tsendtime,
		yr, mo, da, hr, 
		0.0393701 * stats precip_in
	from met
	order by met.tsendtime
) to :'fname' WITH HEADER CSV;"
# turn off the expansion of the asterisk
set -f
echo -e $raster_sql > $raster_sql_file 
cat $raster_sql_file | psql -h $db_host $db_name
