************************************************************************
*** Program to read data time series data from csv files generated by***
*** Lauren Hay's xyz model and insert these new values into a        ***
*** wdm.  This uses wdm subroutines located in lib3.2/src/wdtms1.f   ***
*** It will be used for prad wdms                                    ***
*** Created by: Mike Barnes 4/29/11                                  ***
*** Adopted and Edited by: Gopal Bhatt 1/31/12                       ***
************************************************************************
      implicit none
C     ERROR CODES       
      integer err, retcod
C     FILE AND INPUT NAMES
      character*6 lseg
      character*64 wdmpname,mesname
      character*200 dfnam
      character*200 sfnam
      character*100 datasource, version, year
C     SIZE OF INPUT NAMES
      integer lendatasource, lenversion, lenyear
C     SIZE OF DATE ARRAYS
      integer ndate
      parameter (ndate=6)
C     START AND END DATES IN WDM FORMAT         
      integer sdate(ndate), edate(ndate)
      integer insdate(ndate), inedate(ndate)
      integer tmpsdate(ndate), tmpedate(ndate)  
C     WDM IO PARAMS
      integer tcode, tstep, dtran, qualfg, dtovwr
      parameter (tcode=3, tstep=1, dtran=0, qualfg=0, dtovwr=1)
C     FILE UNIT NUMBERS      
      integer datafile, wdmput, mesfile, statfile
      parameter (datafile=13, wdmput=12,mesfile=9)
C     INTEGER COUNTER AND DATA SET NUMBER
      integer i, dsn
C     VARIABLES FOR CHECKING CLIMATE INSERT DATA
      integer oldyear
      real dacc
C     ARRAY SIZES AND NUMBER OF VALUES IN TIMESERIES 
      integer nvals, delnvals,tmpnvals1,tmpnvals2, ndaymax
      parameter (ndaymax=12500)
      real hval(ndaymax*24)
C     INPUT BUFFER FOR CLIMATE INSERT      
      real csvdata(ndaymax*24)
      integer counter, totalcount, expectedcount
      parameter(expectedcount=87672)
      integer time(expectedcount+1,4)

      real PrcOldAvgAnn, PrcNewAvgAnn, PrcDifAvgAnn, PrcDelAvgAnn
      real dval(ndaymax)
      real dprcdif(ndaymax)
      real dprcfac(ndaymax)
      real dprcold, dprcnew
      real DatOldAvgAnn,DatNewAvgAnn,DatDifAvgAnn,DatDelAvgAnn
      real DatDifPerPrcDif
      integer idays, ndays

      data dval /ndaymax*0/
      data dprcdif /ndaymax*0/
      data dprcfac /ndaymax*1/

      real WNOXPRCSLP, WNOXPRCINT
      real WNHXPRCSLP, WNHXPRCINT

      ! *** IT WOULD BE BETTER TO USE A CONFIG FILE AND READ THAN DEFINE
      !data WNOXPRCSLP /0.797/
      !data WNOXPRCINT /0.000/
      !data WNHXPRCSLP /0.971/
      !data WNHXPRCINT /0.000/
      include 'sensitivity.inc'

******************** END SPECIFICATIONS ********************************

      read(*,*) lseg, datasource, version, year
      call lencl(datasource,lendatasource)
      call lencl(version,lenversion)
      call lencl(year, lenyear)
      print*, lseg

**********start and end dates for entire timeseries*********************
      sdate(1) = 1984
      sdate(2) = 1
      sdate(3) = 1
      sdate(4) = 0
      sdate(5) = 0
      sdate(6) = 0
      
      edate(1) = 2005
      edate(2) = 12
      edate(3) = 31
      edate(4) = 24
      edate(5) = 0
      edate(6) = 0

**********start and end dates for climate modified insert***************

      insdate(1) = 1991
      insdate(2) = 1
      insdate(3) = 1
      insdate(4) = 0
      insdate(5) = 0
      insdate(6) = 0

      inedate(1) = 2000
      inedate(2) = 12
      inedate(3) = 31
      inedate(4) = 24
      inedate(5) = 0
      inedate(6) = 0
**********start and end dates for modified Jan 96 temperature data******
      tmpsdate(1) = 1996 
      tmpsdate(2) = 1
      tmpsdate(3) = 18
      tmpsdate(4) = 0
      tmpsdate(5) = 0
      tmpsdate(6) = 0

      tmpedate(1) = 1996
      tmpedate(2) = 1
      tmpedate(3) = 21
      tmpedate(4) = 24
      tmpedate(5) = 0
      tmpedate(6) = 0

*********** Open WDM and Data file *************************************
C      mesname= './message.wdm'
C      call wdbopn(mesfile,mesname,1,retcod)  ! open mesfile read only
C      if (retcod.ne.0) stop 'error opening message wdm' 
      wdmpname = 'prad_'//lseg//'.wdm'
      call wdbopn(wdmput,wdmpname,0,retcod)  ! open read/write 
      if (retcod.ne.0) then
             print*, 'retcod = ', retcod 
             stop 'error opening wdm'
      end if
*********** HPRC *******************************************************
      dfnam = '../../../'//
     .        'input/unformatted/././'//
     .       datasource(:lendatasource)//'/'//version(:lenversion)//
     .       '/'//year(:lenyear)//'/'//lseg//'.PPT'
C      dfnam = lseg//'.TMP'
      print*,dfnam
      open(datafile,file=dfnam,status='old',iostat=err)

      if (err.ne.0) stop 'error opening .PPT file '
      sfnam    = 'annual_stats.txt'
C      open(statfile,file=sfnam,access='APPEND',status='UNKNOWN',
C     . iostat=err)
      open(statfile,file=sfnam,access='sequential',status='UNKNOWN',
     . position="append",iostat=err)
      if (err.ne.0) stop 'error opening STAT file '
*************read in the data to local variables************************
      counter = 1
      do
           read(datafile,111,end=222)
     .     time(counter,1),time(counter,2),
     .     time(counter,3),time(counter,4),
     .     csvdata(counter) 
           counter=counter+1
      end do
 111  FORMAT(I4,2X,I2,2X,I2,2X,I2,2X,F10.4)
 222  continue
      close (datafile)
      totalcount = counter-1
      print*,totalcount,' ', expectedcount, ' << '
      if(totalcount.ne.expectedcount) stop 'check input file length'
*************read in the old wdm timeseries and insert new data*********
      dsn = 2000 
      print*,lseg,' ',dsn,' HPRC'

      call timdif(
     I            sdate,edate,tcode,tstep,
     O            nvals)

      call wdtget(
     I            wdmput,dsn,tstep,sdate,nvals,
     I            dtran, qualfg, tcode,
     O            hval, retcod)

      if (retcod.ne.0) stop 'error getting wdm timeseries'

************find spot in timeseries to insert new data******************
      call timdif(
     I            sdate,insdate,tcode,tstep,
     O            delnvals)
************insert climate modified temperature data********************
      !do i = 1,ndaymax
      !   dprc(i) = 0
      !end do
      idays = 1
      dprcold = 0
      dprcnew = 0
      PrcOldAvgAnn = 0
      PrcNewAvgAnn = 0
      PrcDifAvgAnn = 0
      do i = 1, totalcount
           dprcold = dprcold + hval(delnvals+i)
           dprcnew = dprcnew + csvdata(i)
           !dprc(idays) = dprc(idays) + (csvdata(i)-hval(delnvals+i))
           if ( mod(i,24) .eq. 0 ) then
              dprcdif(idays) = dprcnew - dprcold
              !print*,'prc',dprcold,dprcnew
              if (dprcold .gt. 0) dprcfac(idays) = dprcnew / dprcold
              PrcDifAvgAnn = PrcDifAvgAnn + dprcdif(idays)
              idays = idays + 1
              dprcold = 0
              dprcnew = 0
           endif
           PrcOldAvgAnn = PrcOldAvgAnn + hval(delnvals+i)
           hval(delnvals+i)=csvdata(i)
           PrcNewAvgAnn = PrcNewAvgAnn + hval(delnvals+i)
      end do 
      idays = idays - 1
      PrcOldAvgAnn = PrcOldAvgAnn / ( inedate(1)-insdate(1)+1 )
      PrcNewAvgAnn = PrcNewAvgAnn / ( inedate(1)-insdate(1)+1 )
      PrcDifAvgAnn = PrcDifAvgAnn / ( inedate(1)-insdate(1)+1 )
      PrcDelAvgAnn = 100 * PrcDifAvgAnn / PrcOldAvgAnn
      print*,'... rainfall baseline  = ',PrcOldAvgAnn,' inches'
      print*,'... rainfall climate   = ',PrcNewAvgAnn,' inches'
      print*,'... diff rainfall, in  = ',PrcNewAvgAnn-PrcOldAvgAnn
      print*,'... diff daily, in     = ',PrcDifAvgAnn
      print*,'... delta daily in %   = ',PrcDelAvgAnn

************check that the end date is the expected end date************
      do i = 1, 4
           print*,time(totalcount,i),inedate(i)
           if (time(totalcount,i).ne.inedate(i)) stop 'wrong end date' 
      end do
************check for valid PRC range in all data***********************
      do i = 1, nvals
           if(hval(i).lt.0.or.hval(i).gt.9) then
                 print*, 'precip= ', hval(i)
                 stop 'data outside valid PRC range'
           end if
      end do
************check for valid range using annual sum and print************
      write(statfile,*) lseg
      oldyear = time(1,1)
      dacc = 0.0
      do i = 1,totalcount
           if(oldyear.ne.time(i,1)) then
                   print*,lseg,',',oldyear,',',dacc
                   write(statfile,*) lseg,',',oldyear,',',dacc
                   if(dacc.lt.20.or.dacc.gt.95) then
                           stop 'PRC out of range'
                   end if
                   oldyear = time(i,1)
                   dacc = 0.0
           end if
           dacc = dacc + csvdata(i)
      end do
      print*,lseg,',',oldyear,',',dacc
      write(statfile,*) lseg,',',oldyear,',',dacc
************write back to the wdm file**********************************
      print*,'writing to ', wdmpname
      call wdtput(
     I            wdmput,dsn,tstep,sdate,nvals,
     I            dtovwr, qualfg, tcode,hval,
     O            retcod)
      if (retcod.ne.0) then
            print*, 'retcod = ', retcod
            stop 'error writing wdm'
      end if 
************write back to the wdm file**********************************


********* Adjust WET NOX ***************
      dsn = 2001
      call getdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)
      DatOldAvgAnn = 0
      do i = 1,ndays
         DatOldAvgAnn = DatOldAvgAnn + dval(i)
      end do
      DatOldAvgAnn = DatOldAvgAnn / ( inedate(1)-insdate(1)+1 )
      print*,'... Wet NOX lb/ac/yr   = ',DatOldAvgAnn
      DatDelAvgAnn = WNOXPRCSLP * PrcDelAvgAnn + WNOXPRCINT
      print*,'... WNOX % Change Est  = ',DatDelAvgAnn
      DatDifAvgAnn = DatOldAvgAnn * DatDelAvgAnn / 100
      DatDifPerPrcDif = DatDifAvgAnn / PrcDifAvgAnn ! lb/in
      print*,'... WNOX dif lb/ac/yr  = ',DatDifAvgAnn
      print*,'... WNOX per unit rain = ',DatDifPerPrcDif
      DatNewAvgAnn = 0
      do i = 1,ndays
         dval(i) = dval(i) + DatDifPerPrcDif * dprcdif(i)
         DatNewAvgAnn = DatNewAvgAnn + dval(i)
      end do
      DatNewAvgAnn = DatNewAvgAnn / ( inedate(1)-insdate(1)+1 )
      print*,'... Wet NOX lb/ac/yr   = ',DatNewAvgAnn
      call putdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)


********* Adjust WET NHX ***************
      dsn = 2002
      call getdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)
      DatOldAvgAnn = 0
      do i = 1,ndays
         DatOldAvgAnn = DatOldAvgAnn + dval(i)
      end do
      DatOldAvgAnn = DatOldAvgAnn / ( inedate(1)-insdate(1)+1 )
      print*,'... Wet NHX lb/ac/yr   = ',DatOldAvgAnn
      DatDelAvgAnn = WNHXPRCSLP * PrcDelAvgAnn + WNHXPRCINT
      print*,'... WNHX % Change Est  = ',DatDelAvgAnn
      DatDifAvgAnn = DatOldAvgAnn * DatDelAvgAnn / 100
      DatDifPerPrcDif = DatDifAvgAnn / PrcDifAvgAnn ! lb/in
      print*,'... WNHX dif lb/ac/yr  = ',DatDifAvgAnn
      print*,'... WNHX per unit rain = ',DatDifPerPrcDif
      DatNewAvgAnn = 0
      do i = 1,ndays
         dval(i) = dval(i) + DatDifPerPrcDif * dprcdif(i)
         DatNewAvgAnn = DatNewAvgAnn + dval(i)
      end do
      DatNewAvgAnn = DatNewAvgAnn / ( inedate(1)-insdate(1)+1 )
      print*,'... Wet NHX lb/ac/yr   = ',DatNewAvgAnn
      call putdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)


********* Adjust WET ORN ***************
      dsn = 2005
      call getdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)
      DatOldAvgAnn = 0
      DatNewAvgAnn = 0
      do i = 1,ndays
         DatOldAvgAnn = DatOldAvgAnn + dval(i)
         dval(i) = dval(i) * dprcfac(i)
         DatNewAvgAnn = DatNewAvgAnn + dval(i)
      end do
      DatOldAvgAnn = DatOldAvgAnn / ( inedate(1)-insdate(1)+1 )
      DatNewAvgAnn = DatNewAvgAnn / ( inedate(1)-insdate(1)+1 )
      print*,'... ORGN baseline      = ',DatOldAvgAnn
      print*,'... ORGN climate       = ',DatNewAvgAnn
      call putdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)


********* Adjust WET PO4 ***************
      dsn = 2006
      call getdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)
      DatOldAvgAnn = 0
      DatNewAvgAnn = 0
      do i = 1,ndays
         DatOldAvgAnn = DatOldAvgAnn + dval(i)
         dval(i) = dval(i) * dprcfac(i)
         DatNewAvgAnn = DatNewAvgAnn + dval(i)
      end do
      DatOldAvgAnn = DatOldAvgAnn / ( inedate(1)-insdate(1)+1 )
      DatNewAvgAnn = DatNewAvgAnn / ( inedate(1)-insdate(1)+1 )
      print*,'... PO4X baseline      = ',DatOldAvgAnn
      print*,'... PO4X climate       = ',DatNewAvgAnn
      call putdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)


********* Adjust WET ORP ***************
      dsn = 2007
      call getdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)
      DatOldAvgAnn = 0
      DatNewAvgAnn = 0
      do i = 1,ndays
         DatOldAvgAnn = DatOldAvgAnn + dval(i)
         dval(i) = dval(i) * dprcfac(i)
         DatNewAvgAnn = DatNewAvgAnn + dval(i)
      end do
      DatOldAvgAnn = DatOldAvgAnn / ( inedate(1)-insdate(1)+1 )
      DatNewAvgAnn = DatNewAvgAnn / ( inedate(1)-insdate(1)+1 )
      print*,'... ORGP baseline      = ',DatOldAvgAnn
      print*,'... ORGP climate       = ',DatNewAvgAnn
      call putdailydsn(wdmput,insdate,inedate,dsn,ndays,dval)



********* Close Prad WDM file
      call wdflcl(
     I            wdmput,
     O            retcod)
c      if (retcod.ne.0) stop 'error closing wdm'

C      close (mesfile)

      end
